### ISSUE TITLE
Installer gnome shell doesn't register clicks

### ISSUE THREAD

**Issue by cakePhone** [xerolinux/xero_g_iso#1]
The installer for XeroG doesn't respond to clicks at all costs, this makes it impossible to install XeroG (even using tab navigation).

The issue is simple to reproduce, or so I think, just run the most recent version of the installer as of today (06-11-2023) built from the machine you're trying to install to.

Currently trying to get vnc running on this to see if it's a driver issue with the mouse or something else. (If that's how it's supposed to work)

**Comment by TechXero** [comment]
I have tested it multiple times as of today no issues here.. Are yo using Bluetooth mouse ?

**Comment by cakePhone** [comment]
No, I'm using a wired mouse. Also, quick update: it is just mostly the installer. Gnome shell can register *some* clicks, mostly on the dock.

**Comment by TechXero** [comment]
That is strange I just loaded it up on my main machine works just fine .. Hmm... I have no idea.. It's not a problem with ISO since I cannot replicate..

**Comment by cakePhone** [comment]
Yeah, probs a gnome shell issue with drivers. Since mostly it works. Is there a way to manually install this through the command line?

**Comment by TechXero** [comment]
It's supposed to be installed with Calamares no other way.. Can you plz try rebuilding it now ? I just pushed an update to Calamares who knows.. I will test again

**Comment by TechXero** [comment]
Here's video proof nothing's wrong
[Video](https://wormhole.app/BJXJ2#19egKh6nQwOSjpIxwXHAng)

**Comment by cakePhone** [comment]
I decided to just switch distros haha. Sorry about that, I'll close this issue. Thanks for your time.
